version: '3.4'

services:
  inflow:
    image: inflow
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      INFLOW_DB_HOST: db
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    volumes:
      - inflowdb:/var/lib/postgresql/data
      - ./server/models/schema.sql:/docker-entrypoint-initdb.d/init.sql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: inflow
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: inflow
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPASSWORD: postgres

volumes:
  inflowdb:
