version: '3.4'

services:
  inflow:
    image: inflow
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      INFLOW_DB_HOST: db
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    volumes:
      - inflowdb:/var/lib/postgresql/data
      - ./database/testData/dev_dataset.sql:/docker-entrypoint-initdb.d/init.sql
    image: postgres:latest
    restart: always
    environment:
      # these settings align with defaults built into the
      # inflow codebase
      POSTGRES_USER: inflow
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: inflow

      # per the postgres image docs, when storing database data
      # on a mounted volume, postgres needs the database storage
      # location to be a subfolder of that mounted volume, and
      # not the root, so we define `pgdata/` here
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  inflowdb:
