name: inflow-dev

services:
  inflow:
    image: inflow-dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      NODE_ENV: development
      INFLOW_DB_HOST: db
    ports:
      - 8080:8080
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:16
    restart: always
    environment:
      # these settings align with defaults built into the
      # inflow codebase
      POSTGRES_USER: inflow
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: inflow
      # per the postgres image docs, when storing database data
      # on a mounted volume, postgres needs the database storage
      # location to be a subfolder of that mounted volume, and
      # not the root, so we define `pgdata/` here
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - inflowdb:/var/lib/postgresql/data
      - ./database/testData/dev_dataset.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  inflowdb:
