#!/usr/bin/env sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

. "$(dirname "$0")/utils.sh"

REPO_ROOT=$(get_repo_root); IS_REPO=$?
if [ "$IS_REPO" -ne 0 ]; then
    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
    exit 1
fi
cd "$REPO_ROOT" || { echo "ERROR: Failed to navigate to \`$REPO_ROOT\`'."; exit 1; }

load_env || { echo "ERROR: Could not find .env file. Have you set up an environment with ./scripts/env?)" >&2; exit 1; }

if [ "$PROJECT_ENV" = "prod" ]; then
    npm ci --omit=dev --no-fund
else
    npm install
fi
