#!/usr/bin/env sh

REPO_ROOT=$(git rev-parse --show-toplevel)

# clean up webpack artifacts
if [ -d "$REPO_ROOT/build" ]; then
    echo '==> cleaning up webpack build artifacts...'
    rm -rf $REPO_ROOT/build
fi

# clean up node_modules
if [ -d "$REPO_ROOT/node_modules" ]; then
    echo '==> removing node_modules...'
    rm -rf $REPO_ROOT/node_modules
fi

# clean up environment info
if [ -e "$REPO_ROOT/scripts/.env" ]; then
    echo '==> clearing environment settings...'
    rm -f "$REPO_ROOT/scripts/.env"
fi
