#!/usr/bin/env sh

. "$(dirname "$0")/utils.sh"

REPO_ROOT=$(get_repo_root); IS_REPO=$?
if [ "$IS_REPO" -ne 0 ]; then
    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
    exit 1
fi

# clean up webpack artifacts
if [ -d "$REPO_ROOT/build" ]; then
    echo '==> cleaning up webpack build artifacts...'
    rm -rf "$REPO_ROOT/build"
fi

# clean up node_modules
if [ -d "$REPO_ROOT/node_modules" ]; then
    echo '==> removing node_modules...'
    rm -rf "$REPO_ROOT/node_modules"
fi
