#!/usr/bin/env sh

# script/console: Launch a console for the application.

helptext="
Usage: console [SERVICE]
Attach to the SERVICE container.

Optional arguments:
    SERVICE     the name of the docker compose service to attach to
"

. ./scripts/utils.sh

REPO_ROOT=$(get_repo_root); IS_REPO=$?
if [ "$IS_REPO" -ne 0 ]; then
    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
    exit 1
fi
cd "$REPO_ROOT" || { echo "ERROR: Failed to navigate to \`$REPO_ROOT\`'."; exit 1; }

load_env || { echo "ERROR: Could not find .env file. Have you set up an environment with ./scripts/env?)" >&2; exit 1; }

if [ -n "$1" ]; then
    if [ "$1" = "db" ]; then
        docker compose -f "$PROJECT_COMPOSE_FILE" exec db /bin/bash
    elif [ "$1" = "inflow" ]; then
        docker compose -f "$PROJECT_COMPOSE_FILE" exec inflow /bin/bash
    else
        echo "ERROR: Unknown environment ${1}."
        echo "$helptext"
        exit 1
    fi
else
    docker compose -f "$PROJECT_COMPOSE_FILE" exec inflow /bin/bash
fi

exit 0
