#!/usr/bin/env sh

cmd_is_valid() {
    for valid_cmd in "export" "migrate" "reset";
    do
        if [ "$CMD" = "$valid_cmd" ]; then
            return 0
        fi
    done
    return 1
}

REPO_ROOT=$(git rev-parse --show-toplevel)
CMD_DIR="$(realpath $(dirname "$0"))/db_ops"
CMD="$1"

# validate input
if [[ -z "$1" ]] || ! cmd_is_valid; then
    echo "Usage: db (export|migrate|reset)"
    exit 1
fi

cd "$REPO_ROOT"
# try to run subcommand
if [ -x "${CMD_DIR}/${CMD}.sh" ]; then
    shift
    "${CMD_DIR}/${CMD}.sh" "$@"
else
    echo "Error: Script for subcommand `${CMD}` not found."
    exit 1
fi

exit 0
