#!/usr/bin/env sh

. "$(dirname "$0")/utils.sh"

REPO_ROOT=$(get_repo_root); IS_REPO=$?
if [ "$IS_REPO" -ne 0 ]; then
    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
    exit 1
fi
cd "$REPO_ROOT" || { echo "ERROR: Failed to navigate to \`$REPO_ROOT\`'."; exit 1; }


VALID_CMDS="export migrate reset"
CMD_DIR="$(realpath "$(dirname "$0")")/db_ops"
CMD="$1"

# validate input
if [ -z "$CMD" ] || ! in_array "$CMD" "$VALID_CMDS"; then
    echo "Usage: db (export|migrate|reset)"
    exit 1
fi

# try to run subcommand
if [ -x "${CMD_DIR}/${CMD}.sh" ]; then
    shift
    "${CMD_DIR}/${CMD}.sh" "$@"
else
    echo "Error: Script for subcommand `${CMD}` not found."
    exit 1
fi

exit 0
