#!/bin/sh

REPO_ROOT=$(git rev-parse --show-toplevel)
ENV=$(cat "$(dirname "$0")/.env")

cd "$REPO_ROOT"

# start servers
if [ "$ENV" = "production" ]; then
    docker compose -f docker-compose.yml down
else
    # start in dev mode by default
    docker compose -f docker-compose.dev.yml down
fi
