#!/usr/bin/env sh

. "$(dirname "$0")/utils.sh"

REPO_ROOT=$(get_repo_root); IS_REPO=$?
if [ "$IS_REPO" -ne 0 ]; then
    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
    exit 1
fi
cd "$REPO_ROOT" || { echo "ERROR: Failed to navigate to \`$REPO_ROOT\`'."; exit 1; }
}

REPO_ROOT=$(git rev-parse --show-toplevel)
ENV=$(cat "$(dirname "$0")/.env")
cmd="$1"

# validate input
if [[ -z "$1" ]] || ! cmd_is_valid; then
    echo "Usage: server (up|down)"
    exit 1
fi

cd "$REPO_ROOT"

# start servers
if [ "$1" = "up" ]; then
    if [ "$ENV" = "production" ]; then
        # <todo> generate webpack artifacts first
        docker compose -f compose.yml up --build -d
    else
        # start in dev mode by default
        docker compose -f compose.dev.yml up --build -d
        docker compose -f compose.dev.yml exec inflow bash
    fi
elif [ "$1" = "down" ]; then
    if [ "$ENV" = "production" ]; then
        docker compose -f compose.yml down
    else
        # start in dev mode by default
        docker compose -f compose.dev.yml down
    fi
fi
