#!/usr/bin/env sh

# scripts/setup: Set up application for the first time after cloning, or set it
#                back to the initial first unused state.

"$(dirname "$0")/bootstrap"

# build webpack artifacts locally
npm run build

# create any missing database tables
# psql -d $INFLOW_DB_URI -f $REPO_ROOT/database/schema/schema.sql
