#!/usr/bin/env sh

# scripts/setup: Set up application for the first time after cloning, or set it
#                back to the initial first unused state.
. ./scripts/utils.sh

REPO_ROOT=$(get_repo_root); IS_REPO=$?
if [ "$IS_REPO" -ne 0 ]; then
    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
    exit 1
fi
cd "$REPO_ROOT" || { echo "ERROR: Failed to navigate to \`$REPO_ROOT\`'."; exit 1; }

load_env || { echo "ERROR: Could not find .env file. Have you set up an environment with ./scripts/env?)" >&2; exit 1; }

./scripts/bootstrap

# clean up webpack artifacts, if they exist
if [ -d "./build" ]; then
    echo '==> cleaning up webpack build artifacts...'
    rm -rf "./build"
fi

# reset db
./scripts/db reset

if [ "$PROJECT_ENV" = "prod" ]; then
    # build webpack artifacts
    echo '==> Running webpack build...'
    npm run build

    # build new docker image?
fi
