#!/usr/bin/env sh

# scripts/update: Update application to run for its current checkout.

. ./scripts/utils.sh


REPO_ROOT=$(get_repo_root); IS_REPO=$?
if [ "$IS_REPO" -ne 0 ]; then
    echo "ERROR: The current directory does not seem to be within a git repo. Check your working directory and try again."
    exit 1
fi
cd "$REPO_ROOT" || { echo "ERROR: Failed to navigate to \`$REPO_ROOT\`'."; exit 1; }

load_env || { echo "ERROR: Could not find .env file. Have you set up an environment with ./scripts/env?)" >&2; exit 1; }

./scripts/bootstrap

# update npm packages
npm update --save --no-fund

# update database
./scripts/db migrate

# pull latest docker images
docker compose -f "$PROJECT_COMPOSE_FILE" pull --ignore-buildable

# update buildable images
docker compose -f "$PROJECT_COMPOSE_FILE" build

exit 0
